spring:
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          - type: git
            uri: https://github.com/elaris6/SpringCloudConfig
  
  application:
    name: config-Server
